DROP DATABASE IF EXISTS sales_data_db;

CREATE DATABASE sales_data_db;

USE sales_data_db;

SELECT * FROM sales_data;

-- Questions and Queries --

-- Q1: What is the total number of orders in the dataset? --
SELECT COUNT(DISTINCT "Order ID") AS total_orders FROM sales_data;

-- Q2: What is the total revenue generated across all orders? --
SELECT SUM(Sales) AS total_revenue FROM sales_data;

-- Q3: Which products were sold the most by quantity? --
SELECT Product, SUM("Quantity Ordered") AS total_quantity
FROM sales_data
GROUP BY Product
ORDER BY total_quantity DESC
LIMIT 10;

-- Q4: What is the average price of each product?  --
SELECT Product, AVG("Price Each") AS avg_price
FROM sales_data
GROUP BY Product;

-- Q5: What is the monthly revenue trend? --
SELECT Month, SUM(Sales) AS monthly_revenue
FROM sales_data
GROUP BY Month
ORDER BY Month;

-- Q6: During which hour of the day are most orders placed? --
SELECT Hour, COUNT("Order ID") AS total_orders
FROM sales_data
GROUP BY Hour
ORDER BY total_orders DESC
LIMIT 1;

-- Q7: Which cities generate the highest revenue? --
SELECT City, SUM(Sales) AS city_revenue
FROM sales_data
GROUP BY City
ORDER BY city_revenue DESC
LIMIT 10;

-- Q8: What is the average order value (AOV) in each city?  --
SELECT City, AVG(Sales) AS avg_order_value
FROM sales_data
GROUP BY City;

-- Q9: How many unique products are purchased per city?--
SELECT City, COUNT(DISTINCT Product) AS unique_products
FROM sales_data
GROUP BY City;

-- Q10: Which customers (by address) placed the most orders? --
SELECT "Purchase Address", COUNT("Order ID") AS order_count
FROM sales_data
GROUP BY "Purchase Address"
ORDER BY order_count DESC
LIMIT 10;

-- Q11: Which products contribute the most to total revenue? --
SELECT Product, SUM(Sales) AS product_revenue
FROM sales_data
GROUP BY Product
ORDER BY product_revenue DESC
LIMIT 10;

-- Q12: What percentage of total revenue is generated by the top 5 products? --
WITH top_products AS (
    SELECT SUM(Sales) AS top_revenue
    FROM sales_data
    GROUP BY Product
    ORDER BY top_revenue DESC
    LIMIT 5
)
SELECT (SUM(top_revenue) * 100.0) / (SELECT SUM(Sales) FROM sales_data) AS percentage_revenue
FROM top_products;

-- Q13: What is the average number of products sold per order? --
SELECT AVG("Quantity Ordered") AS avg_products_per_order
FROM sales_data;

-- Q14: Which day of the week sees the highest sales? --
SELECT TO_CHAR(TO_DATE("Order Date", 'YYYY-MM-DD HH24:MI:SS'), 'Day') AS weekday, 
       SUM(Sales) AS weekday_sales
FROM sales_data
GROUP BY weekday
ORDER BY weekday_sales DESC
LIMIT 1;

-- Q15: How many orders were placed from unique addresses in each city? --
SELECT City, COUNT(DISTINCT "Purchase Address") AS unique_addresses
FROM sales_data
GROUP BY City
ORDER BY unique_addresses DESC;


























